

name: Build JAR

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for Gradle Wrapper
      run: |
        git update-index --chmod=+x gradlew
      shell: bash

    - name: Build with Gradle Wrapper
      run: .\gradlew.bat build

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: build/libs/*.jar
